version: '3.2'
services:
  sequelize-experiments-db:
    ports:
      - 5432:5432
    image: postgres:10.2
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    volumes:
      - sequelize-experiments-db-volume:/docker-entrypoint-initdb.d
volumes:
  sequelize-experiments-db-volume: